### ISSUE TITLE
Running doesn't run =(

### ISSUE THREAD

**Issue by mrmarselo** [mswhirl/autoflashgui#25]
Connect attempt 1
<Response [200]>
Modem up
Authenticating
Authentication failed, debug values are: []
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/marselo/Desktop/TCHNCLRHCK/autoflashgui-master/libautoflashgui.py", line 25, in srp6authenticate
    token = br.find(lambda tag: tag.has_attr('name') and tag['name'] == 'CSRFtoken')['content']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "autoflashgui.py", line 213, in run
    res = libautoflashgui.mainScript(self.host.get(), self.username.get().encode(), self.password.get().encode(), self.flashfirmware.get(), self.firmwarefile.get(), self.flashSleepDelay, self.methodActionList.get(), self.command.get(), self.splitActive.get(), self.ddnsService.get(), self.connectRetryDelay, self.interCommandDelay)
  File "/Users/marselo/Desktop/TCHNCLRHCK/autoflashgui-master/libautoflashgui.py", line 132, in mainScript
    srp6authenticate(br, host, username, password)
  File "/Users/marselo/Desktop/TCHNCLRHCK/autoflashgui-master/libautoflashgui.py", line 55, in srp6authenticate
    print(_("Exception: ") + str(sys.exc_info()[0]))
NameError: name 'sys' is not defined

**Comment by kevdagoat** [comment]
Before creating a useless issue, please:

1. Make sure you have the latest version of autoflashgui 
2. Have read the wiki and determined your situation: https://hack-Technicolor.rtfd.io

If you need any help, please use the forum:
https://forums.whirlpool.net.au/thread/9vxxl849

**Comment by mswhirl** [comment]
Sorry there is not enough information in the description to diagnose this problem, so I am closing the issue.  I suspect it is a bad password; try changing it to a known username and password then try again.  Regards, Mark.
