### ISSUE TITLE
Cannot run on MacOS

### ISSUE THREAD

**Issue by FrancYescO** [mswhirl/autoflashgui#39]
`pip install robobrowser==0.5.3` and stared:
```
Traceback (most recent call last):
  File "autoflashgui.py", line 14, in <module>
    import os, sys, time, socket, tkinter.filedialog, liblang, libautoflashgui
  File "/Users/francyesco/Downloads/autoflashgui-master/libautoflashgui.py", line 10, in <module>
    from robobrowser import RoboBrowser
  File "/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python3.7/site-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python3.7/site-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python3.7/site-packages/werkzeug/__init__.py)
```
tried `pip install Werkzeug==0.16.1` than
```
['autoflashgui.py'] ['/Users/francyesco/Downloads/autoflashgui-master', '/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python37.zip', '/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python3.7', '/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python3.7/lib-dynload', '/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python3.7/site-packages'] /Users/francyesco/Downloads/autoflashgui-master
['/Users/francyesco/Downloads/autoflashgui-master/autoflashgui.py'] ['/Users/francyesco/Downloads/autoflashgui-master', '/Users/francyesco/Downloads/autoflashgui-master', '/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python37.zip', '/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python3.7', '/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python3.7/lib-dynload', '/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/Users/francyesco/Downloads/autoflashgui-master/venv/lib/python3.7/site-packages'] /Users/francyesco/Downloads/autoflashgui-master
Traceback (most recent call last):
  File "/Users/francyesco/Downloads/autoflashgui-master/liblang.py", line 27, in language_default
    if argv[1] == '-l':
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autoflashgui.py", line 239, in <module>
    liblang.init_language(sys.argv, sys.path, language)
  File "/Users/francyesco/Downloads/autoflashgui-master/liblang.py", line 47, in init_language
    lan = language_default(argv)
  File "/Users/francyesco/Downloads/autoflashgui-master/liblang.py", line 31, in language_default
    lancode2=lancode[0:2]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Pitasi** [comment]
Exactly the same on Linux, thanks for the steps to make it starts.

**Comment by cbatista8a** [comment]
the same on MacOS don’t  work :

python autoflashgui.py        
Traceback (most recent call last):
  File "autoflashgui.py", line 14, in <module>
    import os, sys, time, socket, tkinter.filedialog, liblang, libautoflashgui
  File "liblang.py", line 9, in <module>
    from pathlib import Path
ImportError: No module named pathlib

**Comment by sykhro** [comment]
Worked for me, M1 Macbook running macOS 12.1
```
conda env create -n afgui 
conda activate afgui
conda install werkzeug==0.16.1 robobrowser==0.5.3
python autoflashgui.py -l en
```
<img width="854" alt="image" src="https://user-images.githubusercontent.com/8491400/147355955-7e3cd461-af43-4ffe-ab9f-517e9b76f5b6.png">
